### ISSUE TITLE
Cant import anything

### ISSUE THREAD

**Issue by Lifthraser** [casualchameleon/Bellows#45]
Tried with bellow as the only module activated on a new world.
I click "import youtube playlist"
i paste any youtube playlist but for the exemple: https://www.youtube.com/watch?v=_2xHCZSqpi4
a black and white circle appear and begin to rotate, and never stop.
on console i see this message (i did hide the IP for privacy):

Uncaught (in promise) TypeError: e.match(...) is null
    extractPlaylistKey http://152.228.xxx.xxx:30000/modules/bellows/bellows.js:1
    importPlaylist http://152.228.xxx.xxx:30000/modules/bellows/bellows.js:1
    _onImport http://152.228.xxx.xxx:30000/modules/bellows/bellows.js:1
    activateListeners http://152.228.xxx.xxx:30000/modules/bellows/bellows.js:1
    jQuery 2

**Comment by brother-oak** [comment]
I had this issue too. I think the playlist needs to be your own playlist? At least, that fixed it for me (and I tested it with your example youtube playlist).
Select the playlist you want in YouTube, and instead of pasting that link directly into Bellows, select the Save button in YouTube and save it as a new YouTube playlist of your own (I made it a public playlist - not sure if it would work as a private one). Then you can select your playlist link (select your playlist, then the Share button) and use that link in Bellows and it seems to work (for me, at least)

**Comment by casualchameleon** [comment]
Should be fixed in 0.4.4pre. Please update! Thanks.
